<?php

/**
 * @file
 * Contains drupal_test_suite.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function drupal_test_suite_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the duden_test_suite module.
    case 'help.page.drupal_test_suite':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Test Suite for Drupal functions.') . '</p>';
      return $output;

    default:
  }
}